export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin','estimator','project_manager','sales','viewer')),
    avatar_url TEXT,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS user_preferences (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    default_view TEXT NOT NULL DEFAULT 'today',
    notification_digest TEXT NOT NULL DEFAULT 'daily',
    timezone TEXT NOT NULL DEFAULT 'America/New_York',
    settings_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS companies (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    website TEXT,
    industry TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_id, name)
  )`,
  `CREATE TABLE IF NOT EXISTS contacts (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    title TEXT,
    email TEXT,
    phone TEXT,
    preferred_channel TEXT CHECK (preferred_channel IN ('email','phone','text','unknown')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sites (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    region TEXT,
    postal_code TEXT,
    country TEXT NOT NULL DEFAULT 'US',
    timezone TEXT,
    site_type TEXT CHECK (site_type IN ('data_center','office','warehouse','mixed','unknown')),
    access_notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS inquiries (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    company_id TEXT REFERENCES companies(id) ON DELETE SET NULL,
    contact_id TEXT REFERENCES contacts(id) ON DELETE SET NULL,
    site_id TEXT REFERENCES sites(id) ON DELETE SET NULL,
    owner_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    service_type TEXT NOT NULL CHECK (service_type IN ('data_center_decommissioning','lease_restoration','cable_abatement','hvac_removal','electrical_decommissioning','asset_recovery','other')),
    source_channel TEXT NOT NULL CHECK (source_channel IN ('email','phone','text','manual','photo','web')),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
    workload TEXT NOT NULL DEFAULT 'medium' CHECK (workload IN ('low','medium','high')),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','needs_info','estimating','site_visit','proposal','review','won','lost','archived')),
    estimated_low_cents INTEGER,
    estimated_high_cents INTEGER,
    confidence_score INTEGER NOT NULL DEFAULT 0 CHECK (confidence_score BETWEEN 0 AND 100),
    lease_end_date TEXT,
    requested_due_date TEXT,
    received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_customer_activity_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS inquiry_sources (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK (channel IN ('email','phone','text','manual','photo','web')),
    subject TEXT,
    sender TEXT,
    raw_text TEXT NOT NULL,
    external_message_id TEXT,
    captured_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    captured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS extracted_fields (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    field_key TEXT NOT NULL,
    label TEXT NOT NULL,
    value_text TEXT,
    value_json TEXT,
    confidence_score INTEGER NOT NULL DEFAULT 0 CHECK (confidence_score BETWEEN 0 AND 100),
    source_id TEXT REFERENCES inquiry_sources(id) ON DELETE SET NULL,
    is_verified INTEGER NOT NULL DEFAULT 0 CHECK (is_verified IN (0,1)),
    verified_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(inquiry_id, field_key)
  )`,
  `CREATE TABLE IF NOT EXISTS missing_requirements (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    requirement_key TEXT NOT NULL,
    label TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('scope','timeline','access','equipment','commercial','safety','documentation')),
    severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','blocking')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','requested','received','waived')),
    requested_at TEXT,
    resolved_at TEXT,
    notes TEXT,
    UNIQUE(inquiry_id, requirement_key)
  )`,
  `CREATE TABLE IF NOT EXISTS ai_summaries (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    summary_type TEXT NOT NULL CHECK (summary_type IN ('intake','email','proposal','confidence','scope')),
    body TEXT NOT NULL,
    model_name TEXT,
    confidence_score INTEGER CHECK (confidence_score BETWEEN 0 AND 100),
    generated_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    generated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS ai_runs (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    inquiry_id TEXT REFERENCES inquiries(id) ON DELETE SET NULL,
    run_type TEXT NOT NULL CHECK (run_type IN ('intake_extraction','follow_up_email','proposal','scope','site_checklist','estimate','confidence')),
    provider TEXT NOT NULL DEFAULT 'openai',
    model_name TEXT,
    status TEXT NOT NULL CHECK (status IN ('success','fallback','failed')),
    input_preview TEXT,
    output_json TEXT,
    error_message TEXT,
    latency_ms INTEGER,
    created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS estimates (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','sent','superseded')),
    low_cents INTEGER NOT NULL,
    high_cents INTEGER NOT NULL,
    target_margin_bps INTEGER,
    assumptions TEXT,
    created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TEXT,
    UNIQUE(inquiry_id, version)
  )`,
  `CREATE TABLE IF NOT EXISTS estimate_lines (
    id TEXT PRIMARY KEY,
    estimate_id TEXT NOT NULL REFERENCES estimates(id) ON DELETE CASCADE,
    line_type TEXT NOT NULL CHECK (line_type IN ('labor','logistics','recycling','equipment','subcontractor','contingency','other')),
    description TEXT NOT NULL,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT NOT NULL DEFAULT 'each',
    unit_cost_cents INTEGER NOT NULL,
    total_cents INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS site_visits (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    site_id TEXT REFERENCES sites(id) ON DELETE SET NULL,
    scheduled_start TEXT,
    scheduled_end TEXT,
    status TEXT NOT NULL DEFAULT 'needed' CHECK (status IN ('needed','scheduled','complete','cancelled')),
    assigned_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS checklist_items (
    id TEXT PRIMARY KEY,
    site_visit_id TEXT NOT NULL REFERENCES site_visits(id) ON DELETE CASCADE,
    item_key TEXT NOT NULL,
    label TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','done','not_applicable')),
    completed_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    completed_at TEXT,
    notes TEXT,
    UNIQUE(site_visit_id, item_key)
  )`,
  `CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL CHECK (document_type IN ('follow_up_email','proposal','scope_of_work','site_checklist','estimate','closeout','other')),
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','sent','archived')),
    current_version INTEGER NOT NULL DEFAULT 1,
    created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS document_versions (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    generated_by_ai INTEGER NOT NULL DEFAULT 0 CHECK (generated_by_ai IN (0,1)),
    created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(document_id, version)
  )`,
  `CREATE TABLE IF NOT EXISTS proposals (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    estimate_id TEXT REFERENCES estimates(id) ON DELETE SET NULL,
    document_id TEXT REFERENCES documents(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','review','approved','sent','accepted','rejected')),
    price_low_cents INTEGER,
    price_high_cents INTEGER,
    requires_approval INTEGER NOT NULL DEFAULT 1 CHECK (requires_approval IN (0,1)),
    sent_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS proposal_sections (
    id TEXT PRIMARY KEY,
    proposal_id TEXT NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
    section_key TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    UNIQUE(proposal_id, section_key)
  )`,
  `CREATE TABLE IF NOT EXISTS communications (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    contact_id TEXT REFERENCES contacts(id) ON DELETE SET NULL,
    direction TEXT NOT NULL CHECK (direction IN ('inbound','outbound')),
    channel TEXT NOT NULL CHECK (channel IN ('email','phone','text','internal_note')),
    subject TEXT,
    body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'logged' CHECK (status IN ('draft','sent','received','logged','failed')),
    external_message_id TEXT,
    created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS files (
    id TEXT PRIMARY KEY,
    inquiry_id TEXT REFERENCES inquiries(id) ON DELETE CASCADE,
    site_id TEXT REFERENCES sites(id) ON DELETE SET NULL,
    file_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    size_bytes INTEGER,
    category TEXT NOT NULL CHECK (category IN ('photo','floor_plan','equipment_list','contract','email_attachment','other')),
    uploaded_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS activity_events (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    inquiry_id TEXT REFERENCES inquiries(id) ON DELETE CASCADE,
    actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS integration_connections (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    provider TEXT NOT NULL CHECK (provider IN ('crm','email','calendar','storage','other')),
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'not_connected' CHECK (status IN ('not_connected','connected','error','disabled')),
    external_account_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_id, provider, display_name)
  )`,
  `CREATE TABLE IF NOT EXISTS sync_events (
    id TEXT PRIMARY KEY,
    integration_id TEXT NOT NULL REFERENCES integration_connections(id) ON DELETE CASCADE,
    inquiry_id TEXT REFERENCES inquiries(id) ON DELETE SET NULL,
    status TEXT NOT NULL CHECK (status IN ('queued','success','failed')),
    operation TEXT NOT NULL,
    external_id TEXT,
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS notification_rules (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    rule_key TEXT NOT NULL,
    label TEXT NOT NULL,
    is_enabled INTEGER NOT NULL DEFAULT 1 CHECK (is_enabled IN (0,1)),
    conditions_json TEXT NOT NULL DEFAULT '{}',
    channels_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_id, user_id, rule_key)
  )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    before_json TEXT,
    after_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_inquiries_account_status ON inquiries(account_id, status, priority, received_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_inquiries_owner ON inquiries(owner_user_id, status, received_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_inquiries_company ON inquiries(company_id, received_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_contacts_company ON contacts(company_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sites_company ON sites(company_id)`,
  `CREATE INDEX IF NOT EXISTS idx_missing_inquiry_status ON missing_requirements(inquiry_id, status, severity)`,
  `CREATE INDEX IF NOT EXISTS idx_extracted_inquiry ON extracted_fields(inquiry_id, field_key)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_runs_account_type ON ai_runs(account_id, run_type, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_runs_inquiry ON ai_runs(inquiry_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_documents_inquiry_type ON documents(inquiry_id, document_type, status)`,
  `CREATE INDEX IF NOT EXISTS idx_activity_inquiry ON activity_events(inquiry_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_communications_inquiry ON communications(inquiry_id, occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_files_inquiry ON files(inquiry_id, category)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id, created_at DESC)`
];
