export const inquiries = [
  {
    id: "inq_ntt_ashburn",
    company: "NTT Data",
    title: "NTT Data - Ashburn, VA",
    service: "Data Center Decommissioning",
    location: "Ashburn, VA",
    contact: "Michael Reynolds",
    phone: "(571) 555-0134",
    email: "mreynolds@nttdata.com",
    received: "1h ago",
    last: "2h ago",
    value: "$25k-$45k",
    range: "$28,500 - $45,000",
    workload: "Medium",
    priority: "High",
    confidence: 72,
    missingCount: 3,
    missing: ["site size", "rack count", "access hours"],
    missingFull: [
      "Square footage / suite size",
      "Number of racks / cabinets",
      "Equipment inventory available?",
      "Need data destruction?",
      "Photos or docs from site",
      "Electrical disconnect included?"
    ],
    captured: [
      ["Lease expiration date", "Jul 31, 2025"],
      ["Site access requirements", "After hours"]
    ],
    summary: "Client is requesting decommissioning of a data center suite. Timeline appears urgent with lease end in about 6 weeks. Key details are missing on equipment and access.",
    next: "Send follow-up",
    ai: "Medium"
  },
  {
    id: "inq_cushman_dc",
    company: "Cushman & Wakefield",
    title: "Cushman & Wakefield",
    service: "Cable Abatement",
    location: "Washington, DC",
    contact: "Priya Shah",
    phone: "(202) 555-0178",
    email: "priya.shah@cw.example",
    received: "3h ago",
    last: "4h ago",
    value: "$8k-$14k",
    range: "$8,000 - $14,000",
    workload: "Low",
    priority: "Medium",
    confidence: 68,
    missingCount: 4,
    missing: ["cable volume", "ceiling height"],
    missingFull: ["Ceiling height", "Cable volume", "Work hours", "Floor plan"],
    captured: [["Building", "Reston lease office"], ["Service", "Cable removal"]],
    summary: "Property manager needs cable removed before lease restoration. Scope looks limited, but field quantities and ceiling access are unclear.",
    next: "Request site info",
    ai: "Medium"
  },
  {
    id: "prom",
    company: "Promontory",
    title: "Promontory - DC",
    service: "Lease Restoration",
    location: "Washington, DC",
    contact: "Jordan Lee",
    phone: "(202) 555-0142",
    email: "jlee@promontory.example",
    received: "5h ago",
    last: "5h ago",
    value: "$40k-$75k",
    range: "$40,000 - $75,000",
    workload: "High",
    priority: "High",
    confidence: 81,
    missingCount: 2,
    missing: ["sq. ft", "electrical scope"],
    missingFull: ["Square footage", "Electrical scope"],
    captured: [["Lease deadline", "Aug 12, 2025"], ["Location", "Washington, DC"]],
    summary: "Lease restoration request for a DC facility with likely electrical scope. Needs detailed measurements before estimating.",
    next: "Schedule site visit",
    ai: "High"
  },
  {
    id: "inq_digital_phx",
    company: "Digital Realty",
    title: "Digital Realty - Phoenix, AZ",
    service: "Electrical Decommissioning",
    location: "Phoenix, AZ",
    contact: "Mei Ortiz",
    phone: "(602) 555-0199",
    email: "mei.ortiz@digitalrealty.example",
    received: "1d ago",
    last: "6h ago",
    value: "$12k-$20k",
    range: "$12,000 - $20,000",
    workload: "Low",
    priority: "Medium",
    confidence: 84,
    missingCount: 2,
    missing: ["loads", "access hours"],
    missingFull: ["Electrical loads", "Access hours"],
    captured: [["Service", "Electrical decommissioning"], ["Location", "Phoenix, AZ"]],
    summary: "Electrical-only decommissioning request with basic location and service captured. Load schedule and access window are still needed.",
    next: "Schedule site visit",
    ai: "High"
  },
  {
    id: "edge",
    company: "EdgeConneX",
    title: "EdgeConneX",
    service: "HVAC Removal",
    location: "Dallas, TX",
    contact: "Sam Keller",
    phone: "(214) 555-0108",
    email: "sam.keller@edge.example",
    received: "1d ago",
    last: "8h ago",
    value: "$18k-$32k",
    range: "$18,000 - $32,000",
    workload: "Low",
    priority: "Low",
    confidence: 76,
    missingCount: 1,
    missing: ["utility shutoff"],
    missingFull: ["Utility shutoff"],
    captured: [["Equipment", "CRAC units"], ["Location", "Dallas, TX"]],
    summary: "HVAC removal request for Dallas site. Scope is mostly clear but utility isolation needs confirmation.",
    next: "Confirm utility",
    ai: "Medium"
  }
];
